/** Central product copy for Kept Executive Academy. */

export const COPY = {
  kept: {
    label: "Kept",
    ambientTitle: "Ask the coach",
  },

  landing: {
    metaTitle: "Kept · Executive Academy for B2B sellers",
    metaDescription:
      "Study playbooks, ask situational questions, and follow learning tracks — built for sales executives who sell in 2026.",
    heroEyebrow: "Executive Academy",
    heroTitle: "Executive academy for people who sell in 2026",
    heroBody:
      "Playbooks, situational coach, and structured tracks in one place. Study between calls, not after the quarter ends.",
    pillLibrary: "Library",
    pillCoach: "Coach",
    pillTracks: "Tracks",
    ctaPrimary: "Create free account",
    ctaSecondary: "Sign in",
    heroEmailPlaceholder: "Work email",
    heroEmailHelper: "Next step is signup. Add your name and a password there.",
    pillarsEyebrow: "Three pillars",
    pillarsTitle: "Everything you need to stay sharp",
    pillarsIntro:
      "The same surfaces you use after login — library for depth, coach for the moment, tracks for progression.",
    pillarLibraryTitle: "Library",
    pillarLibraryBody:
      "Psychology, MEDDPICC playbooks, demo stories, and battle cards — open inside the app.",
    pillarCoachTitle: "Coach",
    pillarCoachBody:
      "Ask what to do when the buyer goes quiet, you need a champion, or competition shows up.",
    pillarTracksTitle: "Tracks",
    pillarTracksBody:
      "Follow curated paths in order. Mark materials complete and pick up where you left off.",
    previewEyebrow: "From the library",
    previewTitle: "Materials your team already uses",
    coachExampleEyebrow: "Example question",
    coachExampleTitle: "The buyer went quiet after the demo — what do I do?",
    coachExampleBody:
      "The coach names the blocker, gives 2–3 next steps, and points to the weakest MEDDPICC letter — not a feature tour.",
    coachExampleCta: "Try the coach",
    finalCtaTitle: "Start studying today",
    finalCtaBody:
      "Create an account, open your first track, and ask the coach when a deal gets stuck.",
    finalCtaPrimary: "Create account",
    finalCtaSecondary: "Sign in",
    trustEyebrow: "Built for the field",
    trustBlurb: "Factorial playbooks, MEDDPICC, champion development, and demo mastery — organized in Kept Executive Academy for daily use.",
    trustStats: [
      { value: "19", label: "curated resources" },
      { value: "5", label: "learning tracks" },
      { value: "1", label: "situational coach" },
    ] as const,
    howEyebrow: "How it works",
    howTitle: "Three steps from signup to confident selling",
    howIntro: "No maze of menus — library for depth, coach for the moment, tracks for order.",
    howStep1Title: "Create your account",
    howStep1Body: "Sign up, then choose Kept or Kepta — your friend through library, coach, and tracks.",
    howStep2Title: "Ask the coach or open a playbook",
    howStep2Body: "Stuck on a deal? Describe the situation. Need depth? Open psychology or MEDDPICC in the library.",
    howStep3Title: "Follow a track and mark progress",
    howStep3Body: "Tracks group materials in order. Check items off — progress syncs to your account.",
    howStepCta: "Get started →",
  },

  introTour: {
    metaTitle: "Meet Kept · Executive Academy intro",
    metaDescription:
      "Five quick screens on library, coach, and learning tracks inside Kept Executive Academy.",
    heroCta: "How it works",
    skip: "Skip intro",
    next: "Next",
    back: "Back",
    finishSignedIn: "Open Academy",
    finishSignedOut: "Create free account",
    finishHome: "Back to home",
    checkingSession: "Checking session…",
    progress: ({ step, total }: { step: number; total: number }) => `Step ${step} of ${total}`,
    slides: [
      {
        variant: "bringsCalm",
        title: "Welcome to Executive Academy",
        body: "Kept is your study home for B2B sales — playbooks, situational coach, and tracks you can follow between calls.",
      },
      {
        variant: "keepsContext",
        title: "Library — depth when you need it",
        body: "Open psychology, enterprise and SMB playbooks, demo stories, and battle cards without hunting through folders.",
      },
      {
        variant: "contextBeforeCall",
        title: "Coach — help in the moment",
        body: "Describe what is happening in the deal. The coach gives next steps grounded in MEDDPICC, champion strategy, and your curriculum.",
      },
      {
        variant: "everythingOnTrack",
        title: "Tracks — study in order",
        body: "Learning tracks group materials into paths. Mark items complete and see progress per track.",
      },
      {
        variant: "remindsGently",
        title: "Your next step",
        body: "Start with Buyer psychology foundations or ask the coach a real question from an open deal.",
      },
    ] as const,
  },

  auth: {
    signIn: "Sign in",
    signOutLabel: "Sign out",
    getStarted: "Start free",
    openWorkspaceCta: "Open Academy",
    signedInHint: "Signed in",
    headerAcademyCta: "Academy",
    rootMetaTitle: "Kept · Executive Academy",
    rootMetaDescription:
      "Sales library, situational coach, and learning tracks for B2B executives.",
    ogTitle: "Kept · Executive Academy",
    ogDescription:
      "Study playbooks, ask situational questions, and follow structured tracks.",
    logoAltWordmark: "Kept",
    notFoundTitle: "This page isn't here",
    notFoundHint:
      "The link may be old, or the address has a typo. Head home and we'll get you oriented.",
    homeCtaLabel: "Back to home",
    attributionByline: "Crafted with care by Victor Gutierrez",
  },

  companion: {
    pageMetaTitle: "Choose your friend · Kept Academy",
    eyebrow: "Your study buddy",
    title: "Choose your friend",
    intro:
      "Pick who walks with you through library, tracks, and coach. You can change this anytime in Settings.",
    continueCta: "Continue with my friend",
    changeHint: "You can switch between Kept and Kepta later in Settings.",
    settingsTitle: "Study companion",
    settingsBody: "Who appears on your Academy screens and coach dock.",
    settingsChangeCta: "Change companion",
  },

  academy: {
    pageMetaTitle: "Executive Academy · Kept",
    pageMetaDescription:
      "Sales library, situational coach, and learning tracks for executives.",
    eyebrow: "Executive Academy",
    pageTitle: "What do you need right now?",
    intro: "One clear next step for your deal, your call, or your studying.",
    homeOrPrepLink: "or prep a call instead",
    homeOrStuckLink: "or unstick a deal instead",
    homeContinueEyebrow: "Continue",
    homeExploreTitle: "Explore",
    homeExploreBriefingBody: "Daily sales news, summarized.",
    libraryCardTitle: "Library",
    libraryCardBody: "Playbooks, psychology, battle cards, and demo stories — ready to read.",
    askCardTitle: "Ask the coach",
    askCardBody:
      "Stuck on a deal? Ask what to do now — MEDDPICC gaps, champion, demos, objections.",
    askCardMeta: "Situational AI",
    learnCardTitle: "Learning tracks",
    learnCardBody: "Structured paths with progress. Pick up where you left off.",
    briefingCardTitle: "Briefing",
    briefingCardBody:
      "Daily sales news — summarized and linked to your playbooks and psychology curriculum.",
    briefingCardMeta: "RSS + search",
    briefingMetaTitle: "Briefing · Executive Academy",
    briefingEyebrow: "Sales reading",
    briefingTitle: "Daily briefing",
    briefingIntro:
      "Fresh articles from the sales world, summarized for executives. Each piece points you to related Academy materials when they fit.",
    briefingFilterToday: "Today",
    briefingFilterWeek: "This week",
    briefingFilterAll: "All",
    briefingEmpty:
      "No briefs yet for this range. The daily job fills this feed — check back soon, or widen the filter.",
    briefingLoadError: "Could not load the briefing. Try again in a moment.",
    briefingRelatedLabel: "Related in Academy",
    briefingReadArticle: "Read article",
    briefingAskCoach: "Ask the coach",
    continueTitle: "Continue studying",
    continueBody: "Jump back to your last track or material.",
    continueCta: "Resume",
    continueEmpty: "No recent activity yet. Open a track or library resource to start.",
    startGuideEyebrow: "New here?",
    startGuideTitle: "Start in 3 clear steps",
    startGuideBody: "Follow this path once — then use Library, Coach, or Tracks whenever you need them.",
    startStep1Title: "Take the 2-minute tour",
    startStep1Body: "See where library, coach, and tracks live.",
    startStep2Title: "Open your first learning track",
    startStep2Body: "Buyer psychology foundations is the best starting point.",
    startStep3Title: "Ask the coach a real question",
    startStep3Body: "Paste a deal situation — get next steps, not theory.",
    libraryEmptyIllustration: "Try a different search or clear filters.",
    situationTitle: "In a tough moment right now?",
    situationBody:
      "Tell the coach about the deal — stage, champion, what’s stuck. Get next steps in under a minute.",
    situationCta: "Ask what to do now",
    situationStuckCta: "Deal stuck",
    situationPrepCta: "Prep a call",
    recentSessionsTitle: "Recent situations",
    recentSessionsEmpty: "No saved situations yet. Start with Deal stuck or Prep a call.",
    recentSessionsResume: "Resume",
    browseLibraryCta: "Browse library",
    stuckMetaTitle: "Deal stuck · Executive Academy",
    stuckEyebrow: "Situational coach",
    stuckTitle: "Deal stuck",
    stuckIntro:
      "Fill in what you know. The coach will name the blocker and give 2–3 next steps.",
    stuckSituationLabel: "What’s stuck?",
    stuckSituationPlaceholder: "Buyer went quiet after demo… no champion… legal stalled…",
    stuckSubmit: "Ask the coach",
    prepMetaTitle: "Prep a call · Executive Academy",
    prepEyebrow: "Situational coach",
    prepTitle: "Prep a call",
    prepIntro:
      "Set the stage for your next conversation. The coach builds a short agenda and risk checklist.",
    prepSituationLabel: "Call goal",
    prepSituationPlaceholder: "Unlock Economic Buyer… test for champion… push back on full demo…",
    prepSubmit: "Prep with coach",
    situationFormDealLabel: "Deal or account (optional)",
    situationFormDealPlaceholder: "Acme Corp — HRIS renewal",
    situationFormStageLabel: "Stage",
    situationFormStagePlaceholder: "Select stage",
    situationFormChampionLabel: "Do you have a champion?",
    situationFormChampionYes: "Yes",
    situationFormChampionNo: "No",
    situationFormChampionUnsure: "Unsure",
    situationFormCompetitorLabel: "Competitor (optional)",
    situationFormCompetitorPlaceholder: "HiBob, Personio, status quo…",
    situationFormCancel: "Cancel",
    situationFormSaving: "Starting session…",
    situationFormError: "Could not start the session. Try again.",
    roleplayMetaTitle: "Roleplay · Executive Academy",
    roleplayEyebrow: "Practice arena",
    roleplayTitle: "Roleplay a buyer",
    roleplayIntro:
      "Pick who you're selling to and how tough they are. The AI plays the buyer — you practice the call. End anytime to get scored feedback.",
    roleplayPersonaLabel: "Who's the buyer?",
    roleplayScenarioLabel: "Scenario",
    roleplayDifficultyLabel: "Difficulty",
    roleplayContextLabel: "Extra context (optional)",
    roleplayContextPlaceholder:
      "Mid-market retailer, 800 employees, runs HR on spreadsheets today…",
    roleplaySubmit: "Start roleplay",
    roleplayStarting: "Calling the buyer…",
    roleplayPersonaRequired: "Pick a buyer persona first.",
    roleplayEndCta: "End roleplay & get feedback",
    roleplayHomeLink: "practice with a roleplay",
    roleplayEmptyCta: "Roleplay a buyer",
    briefingUseOnCall: "Use on today’s call",
    briefingUseOnCallTitle: "Use on today’s call",
    briefingUseOnCallBody: "Link this article to a live deal, then ask the coach how to use it.",
    briefingUseOnCallSubmit: "Open coach",
    briefingUseOnCallCancel: "Cancel",
    askSessionBanner: (label: string) => `Deal context: ${label}`,
    askResumeTitle: "Resume a situation",
    askEmptyStuck: "Deal stuck",
    askEmptyPrep: "Prep a call",
    quizMetaTitle: "Track quiz · Executive Academy",
    quizTakeCta: "Take quiz",
    quizRetakeCta: "Retake quiz",
    quizPassedBadge: "Quiz passed",
    quizTitle: (track: string) => `${track} — quiz`,
    quizIntro: "Short check — pick the best answer. Pass with 70% or higher.",
    quizSubmit: "See results",
    quizScore: (score: number, total: number) => `You scored ${score} / ${total}`,
    quizPassed: "Passed — nice work.",
    quizFailed: "Not quite — review the track and try again.",
    quizBackToTracks: "Back to tracks",
    quizExplanation: "Why",
    lmsFutureBody:
      "Quizzes are live on B2B buying fundamentals and MEDDPICC and champion. More tracks and team assignments are on the roadmap.",
    backToHub: "Back to Academy",
    backToLibrary: "Back to library",
    libraryMetaTitle: "Library · Executive Academy",
    libraryTitle: "Curriculum library",
    libraryIntro:
      "Open any resource inside the app or in a new tab. Search by topic or filter by type.",
    librarySearchPlaceholder: "Search playbooks, MEDDPICC, champion…",
    libraryEmpty: "No resources match. Try another filter or search term.",
    readerNotFound: "This resource was not found.",
    readerLoading: "Loading…",
    readerLoadError: "Could not load this file.",
    openNewTab: "Open in new tab",
    askAboutThis: "Ask the coach",
    askContextBanner: (topic: string) => `Context: ${topic}`,
    askContextDraft: (title: string) =>
      `I'm studying "${title}". Help me apply it to a live deal — what should I focus on next?`,
    askBriefingDraft: (title: string) =>
      `I just read this sales briefing: "${title}". How should I use it on my next call?`,
    markComplete: "Mark as completed",
    markIncomplete: "Mark as not completed",
    askMetaTitle: "Ask coach · Executive Academy",
    askTitle: "Executive coach",
    askSubtitle: "Situational help — MEDDPICC, champion, demos, objections.",
    askEmptyHint: "Describe your deal or question. Example situations below.",
    askSuggestions: [
      "The buyer went quiet after demo — what do I do?",
      "How do I find my champion in this account?",
      "They want to see every module — how do I push back?",
      "HiBob is on the shortlist — what's my opening?",
    ],
    askPlaceholder: "What's happening in this deal?",
    askNewChat: "New chat",
    askThinking: "Thinking…",
    askSendAria: "Send question",
    askErrorGeneric: "Something went wrong. Try again.",
    learnMetaTitle: "Learning tracks · Executive Academy",
    learnTitle: "Learning tracks",
    learnIntro:
      "Tracks group library content into paths. Mark materials complete as you go — progress syncs to your account.",
    trackComingSoon: "Coming soon",
    trackEmpty: "Content will be added to this track.",
    trackProgress: (pct: number) => `${pct}% complete`,
    studyStreakLabel: (n: number) =>
      n === 1 ? "1-day study streak" : `${n}-day study streak`,
    studyStreakEmpty: "Study today to start your streak",
    lmsFutureTitle: "More coming",
    dockLabel: "Home",
    dockLibrary: "Library",
    dockCoach: "Coach",
    dockTracks: "Tracks",
    coachDockTitle: "Open coach",
  },

  settings: {
    pageMetaTitle: "Settings · Kept",
    eyebrow: "Settings",
    pageTitle: "Your account",
    pageIntro: "Profile details and sign out. No integrations — just your study space.",
    profileSection: "Profile",
    nameLabel: "Display name",
    emailLabel: "Email",
    emailHint: "Email is managed by your sign-in provider.",
    tourLink: "Replay onboarding tour",
    tourLinkHint: "Walk through library, coach, and tracks again.",
    signOutCta: "Sign out",
    savedToast: "Profile updated",
    saveError: "Could not save profile. Try again.",
  },

  appShell: {
    goToAcademy: "Go to Academy",
    dockHome: "Home",
    dockLibrary: "Library",
    dockCoach: "Coach",
    dockTracks: "Tracks",
    dockBriefing: "Briefing",
    dockTour: "Tour",
    dockSettings: "Settings",
    dockSignOut: "Sign out",
    dockApprovals: "Approvals",
    accountMenuLabel: "Account and more",
    footerCredit: "Kept · Executive Academy",
  },

  onboarding: {
    eyebrow: "Quick start",
    title: "New to Executive Academy?",
    bodyLead:
      "Five steps to find the library, ask the coach, and start your first track.",
    replayCta: "Replay tour",
    skipToAcademy: "Skip tour — go to Academy",
    firstRunBannerTitle: "New here? Take the 5-step tour",
    firstRunBannerBody: "Library, coach, and tracks — a quick walkthrough before your first call.",
    firstRunBannerCta: "Start tour",
  },
} as const;
