/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeetKeptRouteImport } from './routes/meet-kept'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStepIdRouteImport } from './routes/onboarding.$stepId'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AcademyLibraryRouteImport } from './routes/academy.library'
import { Route as AcademyLearnRouteImport } from './routes/academy.learn'
import { Route as AcademyAskRouteImport } from './routes/academy.ask'
import { Route as AcademyLibrarySlugRouteImport } from './routes/academy.library.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetKeptRoute = MeetKeptRouteImport.update({
  id: '/meet-kept',
  path: '/meet-kept',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepIdRoute = OnboardingStepIdRouteImport.update({
  id: '/$stepId',
  path: '/$stepId',
  getParentRoute: () => OnboardingRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyLibraryRoute = AcademyLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLearnRoute = AcademyLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAskRoute = AcademyAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLibrarySlugRoute = AcademyLibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/meet-kept': typeof MeetKeptRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/academy/ask': typeof AcademyAskRoute
  '/academy/learn': typeof AcademyLearnRoute
  '/academy/library': typeof AcademyLibraryRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/onboarding/$stepId': typeof OnboardingStepIdRoute
  '/academy/library/$slug': typeof AcademyLibrarySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/meet-kept': typeof MeetKeptRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/academy/ask': typeof AcademyAskRoute
  '/academy/learn': typeof AcademyLearnRoute
  '/academy/library': typeof AcademyLibraryRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/onboarding/$stepId': typeof OnboardingStepIdRoute
  '/academy/library/$slug': typeof AcademyLibrarySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/meet-kept': typeof MeetKeptRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/academy/ask': typeof AcademyAskRoute
  '/academy/learn': typeof AcademyLearnRoute
  '/academy/library': typeof AcademyLibraryRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/onboarding/$stepId': typeof OnboardingStepIdRoute
  '/academy/library/$slug': typeof AcademyLibrarySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/forgot-password'
    | '/intro'
    | '/login'
    | '/meet-kept'
    | '/onboarding'
    | '/pending-approval'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/academy/ask'
    | '/academy/learn'
    | '/academy/library'
    | '/admin/approvals'
    | '/onboarding/$stepId'
    | '/academy/library/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/forgot-password'
    | '/intro'
    | '/login'
    | '/meet-kept'
    | '/onboarding'
    | '/pending-approval'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/academy/ask'
    | '/academy/learn'
    | '/academy/library'
    | '/admin/approvals'
    | '/onboarding/$stepId'
    | '/academy/library/$slug'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/forgot-password'
    | '/intro'
    | '/login'
    | '/meet-kept'
    | '/onboarding'
    | '/pending-approval'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/academy/ask'
    | '/academy/learn'
    | '/academy/library'
    | '/admin/approvals'
    | '/onboarding/$stepId'
    | '/academy/library/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  MeetKeptRoute: typeof MeetKeptRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PendingApprovalRoute: typeof PendingApprovalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-kept': {
      id: '/meet-kept'
      path: '/meet-kept'
      fullPath: '/meet-kept'
      preLoaderRoute: typeof MeetKeptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$stepId': {
      id: '/onboarding/$stepId'
      path: '/$stepId'
      fullPath: '/onboarding/$stepId'
      preLoaderRoute: typeof OnboardingStepIdRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/library': {
      id: '/academy/library'
      path: '/library'
      fullPath: '/academy/library'
      preLoaderRoute: typeof AcademyLibraryRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/learn': {
      id: '/academy/learn'
      path: '/learn'
      fullPath: '/academy/learn'
      preLoaderRoute: typeof AcademyLearnRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/ask': {
      id: '/academy/ask'
      path: '/ask'
      fullPath: '/academy/ask'
      preLoaderRoute: typeof AcademyAskRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/library/$slug': {
      id: '/academy/library/$slug'
      path: '/$slug'
      fullPath: '/academy/library/$slug'
      preLoaderRoute: typeof AcademyLibrarySlugRouteImport
      parentRoute: typeof AcademyLibraryRoute
    }
  }
}

interface AcademyLibraryRouteChildren {
  AcademyLibrarySlugRoute: typeof AcademyLibrarySlugRoute
}

const AcademyLibraryRouteChildren: AcademyLibraryRouteChildren = {
  AcademyLibrarySlugRoute: AcademyLibrarySlugRoute,
}

const AcademyLibraryRouteWithChildren = AcademyLibraryRoute._addFileChildren(
  AcademyLibraryRouteChildren,
)

interface AcademyRouteChildren {
  AcademyAskRoute: typeof AcademyAskRoute
  AcademyLearnRoute: typeof AcademyLearnRoute
  AcademyLibraryRoute: typeof AcademyLibraryRouteWithChildren
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyAskRoute: AcademyAskRoute,
  AcademyLearnRoute: AcademyLearnRoute,
  AcademyLibraryRoute: AcademyLibraryRouteWithChildren,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepIdRoute: typeof OnboardingStepIdRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepIdRoute: OnboardingStepIdRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  MeetKeptRoute: MeetKeptRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PendingApprovalRoute: PendingApprovalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
