/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QualificationRouteImport } from './routes/qualification'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerPartnerIdRouteImport } from './routes/partner.$partnerId'
import { Route as AxisAxisKeyRouteImport } from './routes/axis.$axisKey'
import { Route as PartnerPartnerIdPlanRouteImport } from './routes/partner.$partnerId.plan'
import { Route as PartnerPartnerIdIntelRouteImport } from './routes/partner.$partnerId.intel'
import { Route as PartnerPartnerIdDiagnosticRouteImport } from './routes/partner.$partnerId.diagnostic'
import { Route as PartnerPartnerIdCoachRouteImport } from './routes/partner.$partnerId.coach'
import { Route as PartnerPartnerIdAxesRouteImport } from './routes/partner.$partnerId.axes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificationRoute = QualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPartnerIdRoute = PartnerPartnerIdRouteImport.update({
  id: '/partner/$partnerId',
  path: '/partner/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AxisAxisKeyRoute = AxisAxisKeyRouteImport.update({
  id: '/axis/$axisKey',
  path: '/axis/$axisKey',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPartnerIdPlanRoute = PartnerPartnerIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => PartnerPartnerIdRoute,
} as any)
const PartnerPartnerIdIntelRoute = PartnerPartnerIdIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => PartnerPartnerIdRoute,
} as any)
const PartnerPartnerIdDiagnosticRoute =
  PartnerPartnerIdDiagnosticRouteImport.update({
    id: '/diagnostic',
    path: '/diagnostic',
    getParentRoute: () => PartnerPartnerIdRoute,
  } as any)
const PartnerPartnerIdCoachRoute = PartnerPartnerIdCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => PartnerPartnerIdRoute,
} as any)
const PartnerPartnerIdAxesRoute = PartnerPartnerIdAxesRouteImport.update({
  id: '/axes',
  path: '/axes',
  getParentRoute: () => PartnerPartnerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/qualification': typeof QualificationRoute
  '/signup': typeof SignupRoute
  '/axis/$axisKey': typeof AxisAxisKeyRoute
  '/partner/$partnerId': typeof PartnerPartnerIdRouteWithChildren
  '/partner/$partnerId/axes': typeof PartnerPartnerIdAxesRoute
  '/partner/$partnerId/coach': typeof PartnerPartnerIdCoachRoute
  '/partner/$partnerId/diagnostic': typeof PartnerPartnerIdDiagnosticRoute
  '/partner/$partnerId/intel': typeof PartnerPartnerIdIntelRoute
  '/partner/$partnerId/plan': typeof PartnerPartnerIdPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/qualification': typeof QualificationRoute
  '/signup': typeof SignupRoute
  '/axis/$axisKey': typeof AxisAxisKeyRoute
  '/partner/$partnerId': typeof PartnerPartnerIdRouteWithChildren
  '/partner/$partnerId/axes': typeof PartnerPartnerIdAxesRoute
  '/partner/$partnerId/coach': typeof PartnerPartnerIdCoachRoute
  '/partner/$partnerId/diagnostic': typeof PartnerPartnerIdDiagnosticRoute
  '/partner/$partnerId/intel': typeof PartnerPartnerIdIntelRoute
  '/partner/$partnerId/plan': typeof PartnerPartnerIdPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/qualification': typeof QualificationRoute
  '/signup': typeof SignupRoute
  '/axis/$axisKey': typeof AxisAxisKeyRoute
  '/partner/$partnerId': typeof PartnerPartnerIdRouteWithChildren
  '/partner/$partnerId/axes': typeof PartnerPartnerIdAxesRoute
  '/partner/$partnerId/coach': typeof PartnerPartnerIdCoachRoute
  '/partner/$partnerId/diagnostic': typeof PartnerPartnerIdDiagnosticRoute
  '/partner/$partnerId/intel': typeof PartnerPartnerIdIntelRoute
  '/partner/$partnerId/plan': typeof PartnerPartnerIdPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/partners'
    | '/qualification'
    | '/signup'
    | '/axis/$axisKey'
    | '/partner/$partnerId'
    | '/partner/$partnerId/axes'
    | '/partner/$partnerId/coach'
    | '/partner/$partnerId/diagnostic'
    | '/partner/$partnerId/intel'
    | '/partner/$partnerId/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/partners'
    | '/qualification'
    | '/signup'
    | '/axis/$axisKey'
    | '/partner/$partnerId'
    | '/partner/$partnerId/axes'
    | '/partner/$partnerId/coach'
    | '/partner/$partnerId/diagnostic'
    | '/partner/$partnerId/intel'
    | '/partner/$partnerId/plan'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/partners'
    | '/qualification'
    | '/signup'
    | '/axis/$axisKey'
    | '/partner/$partnerId'
    | '/partner/$partnerId/axes'
    | '/partner/$partnerId/coach'
    | '/partner/$partnerId/diagnostic'
    | '/partner/$partnerId/intel'
    | '/partner/$partnerId/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticRoute: typeof DiagnosticRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  QualificationRoute: typeof QualificationRoute
  SignupRoute: typeof SignupRoute
  AxisAxisKeyRoute: typeof AxisAxisKeyRoute
  PartnerPartnerIdRoute: typeof PartnerPartnerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualification': {
      id: '/qualification'
      path: '/qualification'
      fullPath: '/qualification'
      preLoaderRoute: typeof QualificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/$partnerId': {
      id: '/partner/$partnerId'
      path: '/partner/$partnerId'
      fullPath: '/partner/$partnerId'
      preLoaderRoute: typeof PartnerPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axis/$axisKey': {
      id: '/axis/$axisKey'
      path: '/axis/$axisKey'
      fullPath: '/axis/$axisKey'
      preLoaderRoute: typeof AxisAxisKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/$partnerId/plan': {
      id: '/partner/$partnerId/plan'
      path: '/plan'
      fullPath: '/partner/$partnerId/plan'
      preLoaderRoute: typeof PartnerPartnerIdPlanRouteImport
      parentRoute: typeof PartnerPartnerIdRoute
    }
    '/partner/$partnerId/intel': {
      id: '/partner/$partnerId/intel'
      path: '/intel'
      fullPath: '/partner/$partnerId/intel'
      preLoaderRoute: typeof PartnerPartnerIdIntelRouteImport
      parentRoute: typeof PartnerPartnerIdRoute
    }
    '/partner/$partnerId/diagnostic': {
      id: '/partner/$partnerId/diagnostic'
      path: '/diagnostic'
      fullPath: '/partner/$partnerId/diagnostic'
      preLoaderRoute: typeof PartnerPartnerIdDiagnosticRouteImport
      parentRoute: typeof PartnerPartnerIdRoute
    }
    '/partner/$partnerId/coach': {
      id: '/partner/$partnerId/coach'
      path: '/coach'
      fullPath: '/partner/$partnerId/coach'
      preLoaderRoute: typeof PartnerPartnerIdCoachRouteImport
      parentRoute: typeof PartnerPartnerIdRoute
    }
    '/partner/$partnerId/axes': {
      id: '/partner/$partnerId/axes'
      path: '/axes'
      fullPath: '/partner/$partnerId/axes'
      preLoaderRoute: typeof PartnerPartnerIdAxesRouteImport
      parentRoute: typeof PartnerPartnerIdRoute
    }
  }
}

interface PartnerPartnerIdRouteChildren {
  PartnerPartnerIdAxesRoute: typeof PartnerPartnerIdAxesRoute
  PartnerPartnerIdCoachRoute: typeof PartnerPartnerIdCoachRoute
  PartnerPartnerIdDiagnosticRoute: typeof PartnerPartnerIdDiagnosticRoute
  PartnerPartnerIdIntelRoute: typeof PartnerPartnerIdIntelRoute
  PartnerPartnerIdPlanRoute: typeof PartnerPartnerIdPlanRoute
}

const PartnerPartnerIdRouteChildren: PartnerPartnerIdRouteChildren = {
  PartnerPartnerIdAxesRoute: PartnerPartnerIdAxesRoute,
  PartnerPartnerIdCoachRoute: PartnerPartnerIdCoachRoute,
  PartnerPartnerIdDiagnosticRoute: PartnerPartnerIdDiagnosticRoute,
  PartnerPartnerIdIntelRoute: PartnerPartnerIdIntelRoute,
  PartnerPartnerIdPlanRoute: PartnerPartnerIdPlanRoute,
}

const PartnerPartnerIdRouteWithChildren =
  PartnerPartnerIdRoute._addFileChildren(PartnerPartnerIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticRoute: DiagnosticRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  QualificationRoute: QualificationRoute,
  SignupRoute: SignupRoute,
  AxisAxisKeyRoute: AxisAxisKeyRoute,
  PartnerPartnerIdRoute: PartnerPartnerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
